--ORDER BY KOMUTU(ASC=AZDAN ÇOÐA, DESC=ÇOKTAN AZA)
SELECT P.ProductName,P.UnitPrice FROM PRODUCTS AS P ORDER BY P.UnitPrice DESC
SELECT P.ProductName, P.UnitPrice FROM PRODUCTS AS P ORDER BY P.UnitPrice ASC


--En pahalý ürünü göster.(TOP 1 KOMUTU--KAÇ SIRA GÖSTERÝLMESÝ ÝSTENÝYORSA ONA GÖRE DEÐER VERÝLÝR.)
SELECT TOP 1 P.ProductName, P.UnitPrice FROM PRODUCTS AS P ORDER BY P.UnitPrice DESC


--En ucuz 5 ürünü listele.
SELECT TOP 5 P.ProductName, P.UnitPrice FROM PRODUCTS AS P ORDER BY P.UnitPrice ASC

--STOKTA 1 TANE KALAN ÜRÜNLERÝ MÝKTARLARINA GÖRE AZALAN SIRADA LÝSTELE.
SELECT P.ProductName, P.UnitsInStock, P.UnitPrice FROM PRODUCTS AS P WHERE P.UnitsInStock > 0 AND P.UnitsInStock < 10 ORDER BY P.UnitPrice ASC